gpu_allocation:
  detection:
    auto_discover: true
    capability_check: true
    memory_monitoring: true
    
  scaling_policies:
    minimum_allocation:
      vram_mb: 2048
      compute_percentage: 25
      
    expansion_triggers:
      model_size_threshold_mb: 4096
      concurrent_request_count: 2
      queue_depth: 3
      
    allocation_modes:
      - single_large_instance
      - distributed_small_instances
      - hybrid_dynamic
      
  optimization:
    strategy: "minimize_fragmentation"
    rebalancing_interval_seconds: 30
